baseURL = "http://localhost:1313/a"
languageCode = "en-us"
title = "Javier Álvarez (Medina)"
theme = "hoki"
port = 1313

googleAnalytics = "UA-6602253-10"
enableemoji = true
enableRobotsTXT = true
disableAliases = false

[params]
author = "Javier Álvarez Medina"
role = "Front End developer & Tinybird co-founder"
description = "After almost 9 years at [CARTO](https://carto.com)(& [Vizzuality](https://vizzuality.com)), and discovering how companies are built at [7r](https://7r.ventures), it is time for a [new adventure](https://tinybird.co)..."
keywords = "jmedina,jamedina,xavijam,Javier Álvarez,Javier,Álvarez,Medina,computer,science,tinybird,vizzuality,maps,front-end,carto"
thumbnail = "/a/images/thumbnail.png"
[params.social]
twitter = "xavijam"
github = "xavijam"
linkedin = "javieralvarezmedina"
email = "xavijam@gmail.com"

[taxonomies]
tag = "tags"
category = "categories"