language: node_js

node_js: '9'

cache: yarn

env:
  global:
  - HUGO_VERSION=0.31.1
  - NODE_ENV=production

before_install:
  - mkdir -p bin
  - curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
    -o bin/hugo.tar.gz
  - tar xzvvf bin/hugo.tar.gz -C ./bin

before_script:
  - yarn install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  target_branch: master
  github_token: $GITHUB_TOKEN
  on:
    branch: development