# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://xavij.am
title: xavijam
subtitle: Because technology and environment can live together
author: xavijam
simple_search: http://google.com/search
description: Javier Álvarez Medina personal webpage. Front-end developer at Vizzuality.
keywords: "jmedina,jamedina,xavijam,Javier Álvarez,Javier,Álvarez,Medina,computer,science,vizzuality,maps,biodiversity,front-end,html5,informatics,developer,CartoDB,maps,Leaflet"
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email: xavijam@gmail.com
# RSS feeds can list your email address if you like
email: xavijam@gmail.com
google_analytics_tracking_id: UA-6602253-10


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

root:        /
permalink:   /blog/:year/:month/:day/:title/
source:      ./source
destination: ./public
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
category_dir: blog/categories
keep_files:  ['.git','.svn']
gems:        []


future:      true
pygments:    true

paginate: 4                     # Posts per page on the blog index
paginate_path: "blog/page/:num" # Directory base for pagination URLs eg. /blog/page/2/
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
titlecase:    false             # Converts page and post titles to titlecase

markdown:      rdiscount
rdiscount:
  extensions: [autolink,footnotes,smart]
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        false
watch:       false    # deprecated
server:      false    # deprecated
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://xavij.am
lsi:         false


# ----------------------- #
#  Plugin: jekyll-assets  #
# ----------------------- #
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - js
    - css
    - fonts
  compress:
    js:   'uglifier'
    css:  ~
  cachebust: hard
  gzip: [ text/css, application/javascript ]
  debug: false


# ----------------------- #
#  xavijam: my data       #
# ----------------------- #
jobs:
  # First job at ->> Vizzuality
  - # Array
    company: 
      name:       Vizzuality
      url:        http://vizzuality.com
      location:   Madrid
    position:
      discipline: Front-End
      name:       UI developer
    current_project:
      name:       CartoDB
      url:        http://cartodb.com
    from:         2009-2-14

social:
  twitter:
    name:         Twitter
    username:     xavijam
    url:          http://twitter.com/xavijam
    description:  Sharing and discussing interesting projects
    icon:         twitter
  github: 
    name:         Github
    username:     xavijam
    url:          http://github.com/xavijam
    description:  Coding my humble lines, helping open projects
    icon:         github-alt
  google_plus:
    name:         Google Plus
    username:     +JavierAlvarezMedina
    url:          http://google.com/+JavierAlvarezMedina
    description:  News, projects, friends connection,..
    icon:         google-plus
  linkedin:
    name:         LinkedIn
    username:     javieralvarezmedina
    url:          http://linkedin.com/in/javieralvarezmedina
    description:  Where I connect with other work-mates
    icon:         linkedin