baseURL = "/"
publishDir = "public/a"
languageCode = "en-us"
title = "Javier Álvarez (Medina)"
theme = "hoki"

googleAnalytics = "UA-6602253-10"
enableemoji = true
enableRobotsTXT = true
disableAliases = false

[params]
author = "Javier Álvarez Medina"
siteURL = "http://xavijam.github.io"
description = "Javier Álvarez Medina personal webpage."
keywords = "jmedina,jamedina,xavijam,Javier Álvarez,Javier,Álvarez,Medina,computer,science,vizzuality,maps,biodiversity,front-end,html5,informatics,developer,CARTO,maps,Leaflet,Google Maps"
thumbnail = "/images/thumbnail.png"
[params.social]
twitter = "xavijam"
github = "xavijam"
linkedin = "javieralvarezmedina"
email = "xavijam@gmail.com"

[taxonomies]
tag = "tags"
category = "categories"