baseURL = "/"
publishDir = "public/a"
languageCode = "en-us"
title = "Javier Álvarez (Medina)"
theme = "hoki"

googleAnalytics = "UA-6602253-10"
enableemoji = true
enableRobotsTXT = true
disableAliases = false

[params]
author = "Javier Álvarez Medina"
siteURL = "http://jmed.in/a"
description = "After almost 9 years at [CARTO](https://carto.com)(+ Vizzuality), and discovering how companies are built at [7r](https://7r.ventures), it is time for looking my own adventure..."
keywords = "jmedina,jamedina,xavijam,Javier Álvarez,Javier,Álvarez,Medina,computer,science,tinybird,vizzuality,maps,front-end,carto"
thumbnail = "/images/thumbnail.png"
[params.social]
twitter = "xavijam"
github = "xavijam"
linkedin = "javieralvarezmedina"
email = "xavijam@gmail.com"

[taxonomies]
tag = "tags"
category = "categories"