baseURL = "/"
languageCode = "en-us"
title = "Javier Álvarez (Medina)"

googleAnalytics = "UA-6602253-10"
enableemoji = true
enableRobotsTXT = true
disableAliases = false

[params]
author = "Javier Álvarez Medina"
siteURL = "http://xavijam.github.io"
description = "Javier Álvarez Medina personal webpage."
keywords = "jmedina,jamedina,xavijam,Javier Álvarez,Javier,Álvarez,Medina,computer,science,vizzuality,maps,biodiversity,front-end,html5,informatics,developer,CARTO,maps,Leaflet,Google Maps"
thumbnail = "/images/thumbnail.png"
[params.social]
twitter = "xavijam"
github = "xavijam"
facebook = "jamedina"
linkedin = "javieralvarezmedina"
email = "xavijam@gmail.com"

[taxonomies]
tag = "tags"
category = "categories"

[Languages]
[Languages.en]
languageName = "English"
weight = 1
[Languages.en.menu]
  [[Languages.en.menu.main]]
  identifier = "blog"
  name       = "blog"
  url        = "/blog/"
  weight     = 1

  [[Languages.en.menu.main]]
  identifier = "contact"
  name       = "contact"
  url        = "mailto:xavijam@gmail.com"
  weight     = 2

[Languages.es]
languageName = "Español"
weight = 2
description = "Javier Álvarez Medina página web personal."
[Languages.es.menu]
  [[Languages.es.menu.main]]
  identifier = "blog"
  name       = "blog"
  url        = "/es/blog/"
  weight     = 1

  [[Languages.es.menu.main]]
  identifier = "contacto"
  name       = "contacto"
  url        = "mailto:xavijam@gmail.com"
  weight     = 2